environment: development
container:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: true
  command: ["npx"]
  args: ["nodemon", "--inspect=0.0.0.0", "--ext", "js", "--legacy-watch", "index.js"]
replicaCount: 1
