version: '3'
services:
  mine-support-api-gateway:
    build: .
    image: mine-support-api-gateway
    container_name: mine-support-api-gateway
    command: npm run start-watch
    environment:
      NODE_ENV: development
    ports:
        - "3001:3001"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
