version: '3.4'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-api-gateway-service:
    command: npm run test
    volumes:
      - ./test-output:/usr/src/app/test-output
