version: '3.7'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-api-gateway:
    command: npm run test
    volumes:
      - ./test/:/usr/src/app/test/
      - ./test-output/:/usr/src/app/test-output/
      - ./jest.config.js:/usr/src/app/jest.config.js
