version: '3.7'

services:
  app:
    build:
      context: .
      target: production
    image: ffc-demo-api-gateway
    environment:
      FFC_DEMO_CLAIM_SERVICE: http://ffc-demo-claim-service:3003
      FFC_DEMO_USER_SERVICE: http://ffc-demo-user-service:3002

volumes:
  node_modules:
