apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        environment: {{ .Values.environment }}
      annotations:
        redeployOnChange: "{{ .Values.container.redeployOnChange }}"
    spec:
    
      restartPolicy: {{ .Values.container.restartPolicy }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
        {{- if .Values.container.command }}
        {{- with .Values.container.command }}
          command:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.container.args }}
          args:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          securityContext:
            runAsUser: {{ .Values.container.runAsUser }}
            runAsNonRoot: {{ .Values.container.runAsNonRoot }}
            readOnlyRootFilesystem: {{ .Values.container.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.container.allowPrivilegeEscalation }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
                memory: {{ .Values.container.requestMemory | quote }}
                cpu: {{ .Values.container.requestCpu | quote }}
            limits:
                memory: {{ .Values.container.limitMemory | quote }}
                cpu: {{ .Values.container.limitCpu | quote }}
          env:
            - name: environment
              value: {{ .Values.environment }}
            - name: MINE_SUPPORT_REST_CLIENT_TIMEOUT_IN_MILLIS
              value: {{ .Values.restClientTimeoutMillis | quote }}
            - name: MINE_SUPPORT_USER_SERVICE
              value: {{ .Values.container.userServiceUrl }}:{{ .Values.container.userServicePort }}
            - name: MINE_SUPPORT_CLAIM_SERVICE
              value: {{ .Values.container.claimServiceUrl }}:{{ .Values.container.claimServicePort }}
            - name: PORT
              value: "3001"
