#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set Docker/Kubernetes resource names managed by this script
containerName="ffc-demo-api-gateway"

(
  cd "${projectRoot}"

  helm delete \
    --purge \
    ${containerName}
)
