#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-api-gateway"

(
  cd "${projectRoot}"

  echo "Deploying API Gateway service"
  helm upgrade \
    --atomic \
    --install \
    --namespace ${dockerPrefix} \
    --values helm/development-values.yaml \
    --wait \
    ${dockerPrefix}-service \
    ./helm
)
