{{- define "ffc-demo-api-gateway.container" -}}
name: {{ quote .Values.name }}
env:
- name: environment
  value: {{ quote .Values.environment }}
- name: FFC_DEMO_REST_CLIENT_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.restClientTimeoutMillis }}
- name: FFC_DEMO_USER_SERVICE
  value: {{ quote .Values.container.userServiceUrl }}
- name: FFC_DEMO_CLAIM_SERVICE
  value: {{ quote .Values.container.claimServiceUrl }}
- name: PORT
  value: {{ quote .Values.container.port }}
livenessProbe:
  httpGet:
    path: {{ quote .Values.livenessProbe.path }}
    port: {{ .Values.livenessProbe.port }}
  initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
  failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
readinessProbe:
  httpGet:
    path: {{ quote .Values.readinessProbe.path }}
    port: {{ .Values.readinessProbe.port }}
  initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
  periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
  failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
ports:
- name: http
  containerPort: {{ .Values.container.port }}
  protocol: TCP
{{- end -}}
