{{- include "ffc-helm-library.deployment" (list . "ffc-demo-api-gateway.deployment") -}}
{{- define "ffc-demo-api-gateway.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-demo-api-gateway.container") }}
{{- end -}}
