apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
  labels: {{ include "ffc-demo.labels" . | trimSuffix "\n" | indent 2 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ quote .Values.namespace }}
    app.kubernetes.io/name: {{ quote .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ quote .Values.service.type }}
