{{- include "ffc-helm-library.service" (list . "ffc-demo-api-gateway.service") -}}
{{- define "ffc-demo-api-gateway.service" -}}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "ffc-helm-library.selectorLabels" . | nindent 4 }}
{{- end -}}
