#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

(
  cd "${projectRoot}"
  helm upgrade mine-support-api-gateway --install --namespace mine-support-api-gateway ./helm
)
